version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.3-beta
    container_name: "prisma"
    restart: always
    # dns: 8.8.8.8
    ports:
      - "0.0.0.0:${PORT}:${PORT}"
    # networks:
    #   - prisma-network
    environment:
      PORT: $PORT
      SCHEMA_MANAGER_SECRET: $SCHEMA_MANAGER_SECRET
      SCHEMA_MANAGER_ENDPOINT: ${HOST}:${PORT}/cluster/schema
      SQL_CLIENT_HOST_CLIENT1: $DB_HOST
      SQL_CLIENT_HOST_READONLY_CLIENT1: $DB_HOST
      SQL_CLIENT_HOST: $DB_HOST
      SQL_CLIENT_PORT: $DB_PORT
      SQL_CLIENT_USER: $DB_USERNAME
      SQL_CLIENT_PASSWORD: $DB_PWD
      SQL_CLIENT_CONNECTION_LIMIT: $SQL_CLIENT_CONNECTION_LIMIT
      SQL_INTERNAL_HOST: $DB_HOST
      SQL_INTERNAL_PORT: $DB_PORT
      SQL_INTERNAL_USER: $DB_USERNAME
      SQL_INTERNAL_PASSWORD: $DB_PWD
      SQL_INTERNAL_DATABASE: $DB_NAME
      CLUSTER_ADDRESS: ${HOST}:${PORT}
      SQL_INTERNAL_CONNECTION_LIMIT: $SQL_INTERNAL_CONNECTION_LIMIT
      CLUSTER_PUBLIC_KEY: $CLUSTER_PUBLIC_KEY
      BUGSNAG_API_KEY: ""
      ENABLE_METRICS: "0"
      JAVA_OPTS: "-Xmx1G"

# networks:
#   prisma-network:
#     driver: bridge

  # PORT: $PORT
# SCHEMA_MANAGER_SECRET: $SCHEMA_MANAGER_SECRET
# SCHEMA_MANAGER_ENDPOINT: $SCHEMA_MANAGER_ENDPOINT
# SQL_CLIENT_HOST_CLIENT1: $SQL_CLIENT_HOST
# SQL_CLIENT_HOST_READONLY_CLIENT1: $SQL_CLIENT_HOST
# SQL_CLIENT_HOST: $SQL_CLIENT_HOST
# SQL_CLIENT_PORT: $SQL_CLIENT_PORT
# SQL_CLIENT_USER: $SQL_CLIENT_USER
# SQL_CLIENT_PASSWORD: $SQL_CLIENT_PASSWORD
# SQL_CLIENT_CONNECTION_LIMIT: $SQL_CLIENT_CONNECTION_LIMIT
# SQL_INTERNAL_HOST: $SQL_INTERNAL_HOST
# SQL_INTERNAL_PORT: $SQL_INTERNAL_PORT
# SQL_INTERNAL_USER: $SQL_INTERNAL_USER
# SQL_INTERNAL_PASSWORD: $SQL_INTERNAL_PASSWORD
# SQL_INTERNAL_DATABASE: $SQL_INTERNAL_DATABASE
# CLUSTER_ADDRESS: $CLUSTER_ADDRESS
# SQL_INTERNAL_CONNECTION_LIMIT: $SQL_INTERNAL_CONNECTION_LIMIT
# CLUSTER_PUBLIC_KEY: $CLUSTER_PUBLIC_KEY
# BUGSNAG_API_KEY: ""
# ENABLE_METRICS: "0"
# JAVA_OPTS: "-Xmx1G"