version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.2.8
    container_name: "prisma"
    restart: always
    ports:
      - "0.0.0.0:${PORT}:${PORT}"
    environment:
      PORT: $PORT
      SCHEMA_MANAGER_SECRET: $SCHEMA_MANAGER_SECRET
      SCHEMA_MANAGER_ENDPOINT: ${HOST}:${PORT}/cluster/schema
      CLUSTER_ADDRESS: ${HOST}:${PORT}
      # CLUSTER_PUBLIC_KEY: "${CLUSTER_PUBLIC_KEY}"
      CLUSTER_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\r\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo5gLpcZNsSM/JU95fm+b\r\nmoT1Q1GifzFB3NX0ckSDj4l4ex2rDNFm9cfxbfo7kYLW7zOUTZY7o5KUUnrXkbv2\r\n2lwdfLc0wsMwYAxxIFGC5bz1WnwApbbsSrHAjyEIW1AoNlGOyWFcaX9MYQoiRM03\r\nwhnlx3n0JF9onbde3dagUB+wX3JxTYTYTJYCDqpakAtBCL665lB2jq8x1ZuNvTJC\r\n9qrziPTZipz7rsgZBoq8lMls9eIoU1Q4HzxqFadMbwuG7Lnk74qknquPcoyBSRWg\r\nuLdkcFuyqBWroswjUFyN+ay0DNzA2A6FTV52w4smqIAupuPG8A+Bx+JeI5/83tDb\r\n9QIDAQAB\r\n-----END PUBLIC KEY-----\r\n"
      SQL_CLIENT_HOST_CLIENT1: $DB_HOST
      SQL_CLIENT_HOST_READONLY_CLIENT1: $DB_HOST
      SQL_CLIENT_HOST: $DB_HOST
      SQL_CLIENT_PORT: $DB_PORT
      SQL_CLIENT_USER: $DB_USERNAME
      SQL_CLIENT_PASSWORD: $DB_PWD
      SQL_CLIENT_CONNECTION_LIMIT: $SQL_CLIENT_CONNECTION_LIMIT
      SQL_INTERNAL_HOST: $DB_HOST
      SQL_INTERNAL_PORT: $DB_PORT
      SQL_INTERNAL_USER: $DB_USERNAME
      SQL_INTERNAL_PASSWORD: $DB_PWD
      SQL_INTERNAL_DATABASE: $INTERNAL_GRAPHCOOL_DB_NAME
      SQL_INTERNAL_CONNECTION_LIMIT: $SQL_INTERNAL_CONNECTION_LIMIT
      BUGSNAG_API_KEY: ""
      ENABLE_METRICS: "0"
      JAVA_OPTS: "-Xmx1G"